### ISSUE TITLE
Provide an example application

### ISSUE THREAD

**Issue by msatala** [CodeMettle/jsactor#1]
Please provide an example application. Following the readme isn't sufficient for me (and probably others as well) to be able to implement client-server communication.

**Comment by codingismy11to7** [comment]
Yeah, when I did @ochron's SPA tutorial I implemented it on jsactor instead of autowire - gonna put that up soon.

**Comment by codingismy11to7** [comment]
https://github.com/CodeMettle/jsactor-spa-example
